# https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3fd860446371071d409abfc5b101ecc047df9b37/examples/demo/docker-compose.yaml

services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  otel-collector:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    restart: on-failure
    user: '0:0' # required for logs
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55678:55678" # opencensus receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx/
      args:
        VARIANT: ${NGINX_VARIANT}
    image: nginx-otel:${NGINX_VARIANT}
    volumes:
      - ./config/nginx_module.conf:/etc/nginx/conf.d/opentelemetry_module.conf
      - ./config/nginx_router.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"

# for uptrace

  clickhouse:
    image: clickhouse/clickhouse-server:22.7
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - ch_data:/var/lib/clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  uptrace:
    image: 'uptrace/uptrace:latest'
    volumes:
      - uptrace_data:/var/lib/uptrace
      - ./config/uptrace.yml:/etc/uptrace/uptrace.yml
    ports:
      - '14317:14317'
      - '14318:14318'
    depends_on:
      clickhouse:
        condition: service_healthy

  alertmanager:
    image: prom/alertmanager:v0.24.0
    restart: on-failure
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/config.yml
      - alertmanager_data:/alertmanager
    ports:
      - 9093:9093
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: on-failure
    ports:
      - '8025:8025'

  ## commented-out to stop demo_logs
  # vector:
  #   image: timberio/vector:0.24.X-alpine
  #   volumes:
  #     - ./config/vector.toml:/etc/vector/vector.toml:ro
  #   extra_hosts:
  #     - 'host.docker.internal:host-gateway'


volumes:
  uptrace_data:
    driver: local
  ch_data:
    driver: local
  alertmanager_data:
    driver: local
