# https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3fd860446371071d409abfc5b101ecc047df9b37/examples/demo/otel-collector-config.yaml
# https://opentelemetry.io/docs/collector/configuration/

receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true
        cors:  # https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/confighttp/README.md
          allowed_origins:
            - http://127.0.0.1:3000
            - http://localhost:3000
            - http://lvh.me
            - http://*.lvh.me

  hostmetrics:
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:

exporters:
  otlp:
    endpoint: uptrace:14317
    tls:
      insecure: true
    headers: { 'uptrace-dsn': 'http://project2_secret_token@localhost:14317/2' }

  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/loggingexporter
  logging:
    loglevel: debug

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  resourcedetection:
    detectors: ['system']
  batch:
    send_batch_size: 10000
    timeout: 10s

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, jaeger, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus, otlp]
    metrics/hostmetrics:
      receivers: [hostmetrics]
      processors: [batch, resourcedetection]
      exporters: [otlp]
    logs:  # https://opentelemetry-python.readthedocs.io/en/stable/examples/logs/README.html
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp]
